version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='blog'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='123456'
      - MYSQL_ROOT_PASSWORD='123456'
    volumes:
      - /tmp/django-app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  blog:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE='blog'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='123456'
    volumes:
      - .:/django-app
      - /tmp/django-app/mysqld:/run/mysqld
    depends_on:
      - db
volumes:
  db_data: {}